InfluxDB installation tutorial
storageos/tutorials pull request #37
Opened 2020-09-24 16:00 UTC by timothy-storageos

2020-09-29 12:15 UTC, actionbuddha reviewed
Tim, this is looking good, but it needs some embellishment.

On the first page, we present a cluster that is initialising but with no context:

- In this tutorial we will be installing InfluxDB inside Kubernetes using StorageOS volumes. InfluxDB is a time series database that allows us to bla bla and is a great stateful workload to run on StorageOS
- we should be clear that the cluster is partially installed, and that the user needs to pause to wait for initialisation - make the 'I am ready to go' line in the shell very clear - use the green colouring from the self-eval perhaps?
- the bash code used at init time is visible in the scenario - possible to obfuscate in favour of simple status messages echoed?
- can we use the storageclass 'storageos'? If memory serves the operator creates that in addition to 'fast' (to be confirmed by @Arau )
- mention that the use case draws inspiration from our use case in the docs and give link
- where we are deploying manifests, be clear on the git repo and path we are sourcing from - perhaps have the user check them out in a command to avoid needing to keep this scenario in lock step with the use case repo?
- second page 'Provision storage' is more about 'Installing InfluxDB' I think - change of title?

In short, give more context, and make the style a little more narrative - we're taking the user on a journey here from installing InfluxDB through to putting some data in and using it - that should feel exciting and ultimately satisfying.

2020-09-29 16:09 UTC, Arau commented
>  can we use the storageclass 'storageos'? If memory serves the operator creates that in addition to 'fast' (to be confirmed by @Arau )

We can set the StorageClass name in the CR when installing StorageOS. Not an addition, but instead. The 

`spec.storageClassName` defines the name of the default class.

2020-09-30 07:46 UTC, Arau reviewed
The PR looks good. Any chance @timothy-storageos that you can post the URL that is renders the scenario?

2020-09-30 15:21 UTC, timothy-storageos commented
> Tim, this is looking good, but it needs some embellishment.
> 
> On the first page, we present a cluster that is initialising but with no context:
> 
>     * In this tutorial we will be installing InfluxDB inside Kubernetes using StorageOS volumes. InfluxDB is a time series database that allows us to bla bla and is a great stateful workload to run on StorageOS

_Added much more context to the introductory page_
> 
>     * we should be clear that the cluster is partially installed, and that the user needs to pause to wait for initialisation - make the 'I am ready to go' line in the shell very clear - use the green colouring from the self-eval perhaps?

_Removed a lot of extraneous output to make this line much clearer_

> 
>     * the bash code used at init time is visible in the scenario - possible to obfuscate in favour of simple status messages echoed?

_I'm unable to hide the commands run in foreground scripts on katacoda, and if we run the script in the background, we can't send output to the user. I have tried a workaround, which involves clearing the terminal as part of the script, leaving only the "storageos initialising" text. This means the verbose output disappears almost instantly and also helps make it clear when it's ok to start the tutorial._
> 
>     * can we use the storageclass 'storageos'? If memory serves the operator creates that in addition to 'fast' (to be confirmed by @Arau )

_edited the manifest files and tutorial text to reflect this_
> 
>     * mention that the use case draws inspiration from our use case in the docs and give link

_done_ 
> 
>     * where we are deploying manifests, be clear on the git repo and path we are sourcing from - perhaps have the user check them out in a command to avoid needing to keep this scenario in lock step with the use case repo?

_provided a link to the git repository and some commentary clarifying where the files come from
> 
>     * second page 'Provision storage' is more about 'Installing InfluxDB' I think - change of title?

_title changed_ 
> 
> 
> In short, give more context, and make the style a little more narrative - we're taking the user on a journey here from installing InfluxDB through to putting some data in and using it - that should feel exciting and ultimately satisfying.

_tutorial should now be more clear and satisfying_

2020-09-30 15:22 UTC, timothy-storageos commented on influxdb/000-install-storageos.sh
> +spec:
Thank you

2020-09-30 15:22 UTC, timothy-storageos commented
> The PR looks good. Any chance @timothy-storageos that you can post the URL that is renders the scenario?

https://www.katacoda.com/timothy-storageos/scenarios/influxdb

2020-10-01 07:14 UTC, Arau requested changes

2020-10-01 07:14 UTC, Arau commented on influxdb/020-deploy-pods-service.md
> +`kubectl create -f ./`{{execute}}
When building an scenario we have to keep in mind the maintainability of the solution. We don't want to have to make the same change in 2 different places. In this case, if the use case needs changing then we would have to apply the changes into the scenario. That is not ideal. 

It is better to do the 
```
git clone ..../use-cases
cd storageos-usecases
```

```
kubectl create -f ./influxdb
```

In this way, people can also related to use the same yamls in their clusters if they want to.

2020-10-02 15:54 UTC, avestuk approved these changes

2020-10-02 16:31 UTC, Arau approved these changes

2020-10-02 16:49 UTC, aeroniero33 approved these changes
Nice job! LGTM

2020-10-02 17:04 UTC, actionbuddha approved these changes
LGTM - nice!

2020-10-02 17:09 UTC, merged